export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SESSION_TOKEN_REQUEST = 'SESSION_TOKEN_REQUEST'
export const SESSION_TOKEN_SUCCESS = 'SESSION_TOKEN_SUCCESS'
export const SESSION_TOKEN_FAILURE = 'SESSION_TOKEN_FAILURE'

export const DELETE_TOKEN_REQUEST = 'DELETE_TOKEN_REQUEST'
export const DELETE_TOKEN_SUCCESS = 'DELETE_TOKEN_SUCCESS'